# Generated by Django 4.0.5 on 2022-06-27 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikeapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='bike_milage',
            field=models.IntegerField(default=True, max_length=50),
        ),
        migrations.AddField(
            model_name='bike',
            name='bike_price',
            field=models.BigIntegerField(default=True, max_length=50),
        ),
    ]
