# Generated by Django 4.0.5 on 2022-06-27 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bikeapp', '0002_bike_bike_milage_bike_bike_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='bike_milage',
            field=models.IntegerField(default=True),
        ),
        migrations.AlterField(
            model_name='bike',
            name='bike_price',
            field=models.BigIntegerField(default=True),
        ),
    ]
